version: '3'
services:
    nginx:
      container_name: "nginx"
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 81:81
      depends_on: 
        - rasa
        - action_server
        - chatbot_ui
    rasa:
      container_name: "rasa_server"
      build: 
        context: backend
      ports: 
        - "5065:5065"
    action_server:
      container_name: "action_server"
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
      ports:
        - "9000:9000"  
    chatbot_ui:
      container_name: "chatbot_ui"
      build: 
        context: frontend
      ports: 
        - "3000:3000"
